config/routes.rb
Rails.application.routes.draw do
  get 'skills/new'
  post 'skills/show'
  get 'saludos/new'
  post 'saludos/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  get "home/index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @nombre = "Uriel"
    @skills = ["ruby", "javascript"]
  end

  def saludos
    @nombre = params[:nombre]
  end
end

app/controllers/saludos_controller.rb
class SaludosController < ApplicationController
  def new
  end

  def create
    @nombre = params[:nombre]
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def new
  end

  def show
    @skills = params[:skills].split(",")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/saludos_helper.rb
module SaludosHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/home/index.html.erb
<% nombre = "Uriel" %>

<h1>Hola <%= @nombre %></h1>
<%if nombre == "Uriel"%>
  <p>Equipo de Código Facilito</p>
<%end%>

<% @skills.each do |skill| %>
  <p> <%= skill %> </p>
<%end%>

<%10.times do |i|%>
  <p><%= i %></p>
<%end%>

<p> 4 </p>

<a href="<%= root_path %>"> Home </a>

app/views/home/saludos.html.erb
<p>
  Hola
  <%= @nombre %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HolaMundo7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/saludos/create.html.erb
<h1>
  Hola 
  <%= @nombre %>
</h1>

app/views/saludos/new.html.erb
<%=  form_with url: "/saludos/create", data: {turbo: "false"} do |f| %>
  <%= f.text_field :nombre %>
  <%= f.submit "Enviar" %>
<%end%>

app/views/skills/create.html.erb
<h1>Estas son tus skills registradas</h1>
<ul>
  <%@skills.each do |skill| %>
    <li><%= skill %></li>
  <%end%>
</ul>

app/views/skills/new.html.erb
<div class="columns is-mobile mt-4">
  <div class="column is-half is-offset-one-quarter">
    <h2 class="subtitle">Comparte tus skills</h2>
    <%= form_with url: "/skills/show", data:{turbo: "false"} do |f| %>
      <div class="field">
        <%= f.label :skills, "Coloca tus skills separados por coma", :class => "label"%>
        <div class="control">
          <%= f.text_field :skills, required: true, :class => "input" %>
        </div>
        <p class="help">Ejm: ruby, js, css, php</p>
      </div>
      <div class="field">
        <div class="control">
          <%= f.submit "Enviar", :class => "button is-link" %>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/skills/show.html.erb
<div class="columns is-mobile mt-4">
  <div class="column is-half is-offset-one-quarter">
    <div class="card">
      <header class="card-header">
        <p class="card-header-title">
          Estas son tus skills registradas
        </p>
        <button class="card-header-icon" aria-label="more options">
          <span class="icon">
            <i class="fas fa-angle-down" aria-hidden="true"></i>
          </span>
        </button>
      </header>
      <div class="card-content">
        <div class="content">
          <div class="tags are-medium">
            <%@skills.each do |skill| %>
              <span class="tag"><%= skill %></span>
            <%end%>
          </div>
        </div>
      </div>
      <footer class="card-footer">
        <%= link_to "Crear nuevos skills", skills_new_path(), :class => "card-footer-item" %>
      </footer>
    </div>
  </div>
</div>